### ISSUE TITLE
automatizzare processo download e creazione DB SL

### ISSUE THREAD

**Issue by pigreco** [pigreco/SL-routing#1]
1. dal sito scaricare la sub-regione di interesse [(es: nord-est-latest.osm)](https://download.geofabrik.de/europe/italy.html);
2. un-zipparlo;
3. SpatiaLite fornisce uno specifico strumento CLI che consente di caricare un archivio OSM in un DB: **spatialite_osm_net**, quindi eseguire:
`>spatialite_osm_net -o nord-est-latest.osm -d nord-est.sqlite -T nord-est -m`

Spiegazione veloce:
* **-o** nord-est-latest.osm seleziona l'archivio OSM di input;
* **-d** tnord-est.sqlite seleziona il DB da creare e popolare;
* **-T** nord-est creerà la tabella Geometry che memorizza l'archivio OSM
* **-m** forzerà l'uso di un database in memory, in modo da eseguire l'importazione nel modo più veloce.

quali strumenti servono e come creare un unico script!

**Comment by aborruso** [comment]
Per 1 e 2

```bash
mkdir -p ./dati
dati="https://download.geofabrik.de/europe/italy/isole-latest.osm.bz2"
curl -L "$dati" >./dati/dati.osm.bz2
bzip2 -d ./dati/dati.osm.bz2
```

**Comment by aborruso** [comment]
Il 3 è in questo caso

    spatialite_osm_net -o dati.osm -d dati.sqlite -T nord-est -m

**Comment by pigreco** [comment]
@aborruso 
correggimi se sbaglio, mettendo tutto assieme:

```
mkdir -p ./dati
dati="https://download.geofabrik.de/europe/italy/isole-latest.osm.bz2"
curl -L "$dati" >./dati/dati.osm.bz2
bzip2 -d ./dati/dati.osm.bz2
cd dati/
spatialite_osm_net -o dati.osm -d dati.sqlite -T nord-est -m
```

**Comment by aborruso** [comment]
@pigreco o anche come sotto senza il `cd`

```bash
mkdir -p ./dati
dati="https://download.geofabrik.de/europe/italy/isole-latest.osm.bz2"
curl -L "$dati" >./dati/dati.osm.bz2
bzip2 -d ./dati/dati.osm.bz2
spatialite_osm_net -o ./dati/dati.osm -d ./dati/dati.sqlite -T nord-est -m
```

**Comment by pigreco** [comment]
@aborruso 
grazie per tutto.
chiudo issue.
